apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
